#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mke2fs -T ext4 /dev/vda
mount -t ext4 /dev/vda /vioblk

mount -t ext4 /dev/sdb /scsib
# cp /proc/vmcore /scsib/vmcore

ifconfig eth0 up
ifconfig lo 127.0.0.1

udhcpc -i eth0 -b -R
# ifconfig eth0 down
# ifconfig eth0 up
